test: &default

  # Credentials for REST APIs
  client_id: AYZ-lJXI_MfyDGJhbsvyEd9WmFumsiQYv6Bk8kllS92P5Uy5BPG-QNatr9s7iz4c04dG_jMsEE0M8d6E
  client_secret: EE9woC5Mj4JvgB3nUpS8zO17HH-yROFBr2JYw03TvDsZNjNmt_p6reXC2Z9ureQHO4QYIaxyV8Khn8Bm

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: ltransynergy_api1.gmail.com
  password: 7NX34WPU3WEQ8CLV
  signature: ABDwnh71.BrXhuq2crSWAN--XC9QAYVLoVTspCzFDOoEn2xcR557NE9j
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: ltransynergy@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

  # verbose_logging: true

development:
  <<: *default

production:
  <<: *default
  mode: live
